### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by shreshtadev** [shravanabhat/vue3basics#2]
**Tasks to be completed**
- [x] Please add a registration form.
- [x] Validation for the Login and Registration forms.
- [x] Understanding of REST API Concepts.
- [x] And check how to use a mock REST API to capture the form fields.
     - [ ] [httpbin.org](https://httpbin.org/) can be used for testing

**Comment by shravanabhat** [comment]
All tasks are completed ...I used json server and axios package to fetch
and display API contents and store it in db.json file
